name: Build WeaponPaints

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore WeaponPaints.csproj

      - name: Build
        run: dotnet build WeaponPaints.csproj --configuration Release --no-restore

      - name: Publish DLL artifact
        uses: actions/upload-artifact@v3
        with:
          name: WeaponPaints
          path: bin/Release/net8.0/WeaponPaints.dll
